In [ ]:
#importing numpy
import numpy as np

In [ ]:
# Create a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
array_1d

1D Array: [1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [ ]:
print("Attributes of 1D Array:")
print("Type:", type(array_1d))
print("Data type:", array_1d.dtype)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Number of dimensions:", array_1d.ndim)
print("Number of bytes:", array_1d.nbytes)

Attributes of 1D Array:
Type: <class 'numpy.ndarray'>
Data type: int64
Shape: (5,)
Size: 5
Number of dimensions: 1
Number of bytes: 40


In [ ]:
# Perform some operations on the 1D array
print("Sum of 1D array:", np.sum(array_1d))
print("Mean of 1D array:", np.mean(array_1d))
print("Max element in 1D array:", np.max(array_1d))
print("Min element in 1D array:", np.min(array_1d))

Sum of 1D array: 15
Mean of 1D array: 3.0
Max element in 1D array: 5
Min element in 1D array: 1


In [ ]:
# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", array_2d)


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print("\nAttributes of 2D Array:")
print("Type:", type(array_2d))
print("Data type:", array_2d.dtype)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Number of dimensions:", array_2d.ndim)
print("Number of bytes:", array_2d.nbytes)


Attributes of 2D Array:
Type: <class 'numpy.ndarray'>
Data type: int64
Shape: (3, 3)
Size: 9
Number of dimensions: 2
Number of bytes: 72


In [ ]:
# Perform some operations on the 2D array
print("Sum of all elements in 2D array:", np.sum(array_2d))
print("Sum of elements along rows (axis=0):", np.sum(array_2d, axis=0))
print("Sum of elements along columns (axis=1):", np.sum(array_2d, axis=1))
print("Mean of all elements in 2D array:", np.mean(array_2d))

Sum of all elements in 2D array: 45
Sum of elements along rows (axis=0): [12 15 18]
Sum of elements along columns (axis=1): [ 6 15 24]
Mean of all elements in 2D array: 5.0


In [ ]:
#1D array
arr1=np.array([1,2,3,4,5,6])
print("1D array:",arr1)

1D array: [1 2 3 4 5 6]


In [ ]:
#2D array
arr2=np.array([[1,2,3],[2,3,4],[4,5,6],[7,8,9]])
print("2D array:",arr2)

2D array: [[1 2 3]
 [2 3 4]
 [4 5 6]
 [7 8 9]]


In [ ]:
#understand attributes
print("Type:",type(arr2))
print("Datatype:",arr1.dtype)
print("Shape:",arr1.shape)
print("Size:",arr1.size)
print("Item size:", arr1.itemsize)
print("No. of Dimensions:", arr1.ndim)
print("No. of bytes:", arr1.nbytes)

Type: <class 'numpy.ndarray'>
Datatype: int64
Shape: (6,)
Size: 6
Item size: 8
No. of Dimensions: 1
No. of bytes: 48


In [ ]:
#Creating Special Arrays
#Zeros
arr3=np.zeros((5,2),dtype=int)
print("arr3 with zeroes:",arr3)
arr4=np.ones((3,4),dtype=float)
print("arr4 with ones",arr4)
arr5=np.eye(4,4)
print("arr5 Identity matrix:\n",arr5)
arr6=np.random.rand(3,2)
print("arr6 Random array:\n",arr6)
arr7=np.random.randint(7,size=(2,6))
print("arr7 Random Integer Array:\n",arr7)


arr3 with zeroes: [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
arr4 with ones [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arr5 Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
arr6 Random array:
 [[0.19646886 0.08850666]
 [0.18523367 0.10304029]
 [0.70506807 0.46173582]]
arr7 Random Integer Array:
 [[3 0 1 2 0 5]
 [2 2 6 2 2 2]]


In [ ]:
#Creating Arrays with "arange"
arr8=np.arange(1,10,2)
print('Array created with arange:',arr8)

Array created with arange: [1 3 5 7 9]


In [ ]:
#Creating Arrays with "linspace"
arr9=np.linspace(1,10,50)
print('Array created with linspace requesting 50 elements within 1 to 10:\n',arr9)

Array created with linspace requesting 50 elements within 1 to 10:
 [ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [ ]:
#Slicing
arr10=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr10)
print("Row2:",arr10[1,:])
print("Column2:",arr10[:,1])
print("Elements 7,8,12,13:\n",arr10[1:3,1:3])
print("All Elements:\n",arr10[:,:])
#Strides
print("Strides:\n",arr10[0::2,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row2: [ 6  7  8  9 10]
Column2: [ 2  7 12 17]
Elements 7,8,12,13:
 [[ 7  8]
 [12 13]]
All Elements:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Strides:
 [[ 2  3]
 [12 13]]


In [ ]:
#Masking
arr11=np.array([1,2,3,4,5,6,7,8,9,9])
mask=np.array([0,1,1,0,1,0,1,0,0])
b=arr11[mask]
print(b)

[1 2 2 1 2 1 2 1 1]


In [ ]:
arr12=np.array([[1,2,3,4,5],[6,7,8,9,9]])
print(arr12)
print("Sum:\t",np.sum(arr12))
print("Sum:\t", np.sum(arr12,axis=0))
print("Product: \t",np.prod(arr12))
print("Product: \t",np.prod(arr12,axis=0))
print("Minimum:\t",np.min(arr12,axis=0))
print("Maximum:\t",np.max(arr12,axis=0))
print("Mean:\t",np.mean(arr12,axis=0))
print("Variance:\t",np.var(arr12,axis=0))
print("Standard Deviation:\t",np.std(arr12,axis=0))
print("Average:\t",np.average(arr12,axis=0))
print("Weighted Average:\t",np.average(arr12,weights=[1,2,3,4,5],axis=1))

[[1 2 3 4 5]
 [6 7 8 9 9]]
Sum:	 54
Sum:	 [ 7  9 11 13 14]
Product: 	 3265920
Product: 	 [ 6 14 24 36 45]
Minimum:	 [1 2 3 4 5]
Maximum:	 [6 7 8 9 9]
Mean:	 [3.5 4.5 5.5 6.5 7. ]
Variance:	 [6.25 6.25 6.25 6.25 4.  ]
Standard Deviation:	 [2.5 2.5 2.5 2.5 2. ]
Average:	 [3.5 4.5 5.5 6.5 7. ]
Weighted Average:	 [3.66666667 8.33333333]


In [ ]:
#Scalar Operations
arr13=np.array([1,2,3])
arr14=np.array([4,5,6])
arr15=arr13+arr14
arr16=arr13-arr14
print("Summation:\t",arr15)
print("Difference:\t",arr16)
arr16+=5
print("Previous output after adding 5:",arr16)

##Try out leftout scalar operations

Summation:	 [5 7 9]
Difference:	 [-3 -3 -3]
Previous output after adding 5: [2 2 2]


In [ ]:
#Relational operations
result1=arr15==arr16
print(result1)

[False False False]


In [ ]:
#Try Out other relational operators


In [ ]:
#Trigonometric and Logarithmic operations
arr17=np.array([15,30,45,90])
result7=np.sin(arr17)
print("Sin values:\t",result7)
result8=np.log(arr17)
print("Log values:\t",result8)
#Try other trignomatric functions

Sin values:	 [ 0.65028784 -0.98803162  0.85090352  0.89399666]
Log values:	 [2.7080502  3.40119738 3.80666249 4.49980967]


In [ ]:
# Vector operations: Inner Product, Outer Product, Dot Product, and Matrix Multiplication
import numpy as np

arr18 = np.array([1, 2, 3])
arr19 = np.array([4, 5, 6])

# Inner Product
inner_product = np.inner(arr18, arr19)
print("Inner Product:", inner_product)

# Outer Product
outer_product = np.outer(arr18, arr19)
print("Outer Product:\n", outer_product)

# Dot Product
dot_product = np.dot(arr18, arr19)
print("Dot Product:", dot_product)

# Matrix Multiplication
# For matrix multiplication, the dimensions must be compatible.
# Let's create 2D arrays.
arr20 = np.array([[1, 2], [3, 4]])
arr21 = np.array([[5, 6], [7, 8]])

matrix_product = np.dot(arr20, arr21) # np.dot can also perform matrix multiplication
print("Matrix Multiplication (np.dot):\n", matrix_product)

# Another way to perform matrix multiplication is using the @ operator
matrix_product_at = arr20 @ arr21
print("Matrix Multiplication (@ operator):\n", matrix_product_at)

Inner Product: 32
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Dot Product: 32
Matrix Multiplication (np.dot):
 [[19 22]
 [43 50]]
Matrix Multiplication (@ operator):
 [[19 22]
 [43 50]]
